# FROM eclipse-temurin:25-jdk
# COPY target/*.jar app.jar
# ENTRYPOINT ["java","-jar","/app.jar"]


FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /app

# Apenas dependências (cache)
COPY pom.xml .
RUN mvn dependency:go-offline

# Código virá por volume
EXPOSE 8080

CMD ["mvn", "spring-boot:run"]